version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '13:00'
      timezone: 'Asia/Manila'
    open-pull-requests-limit: 99
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: github-actions
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
      time: '20:00'
      timezone: 'Asia/Manila'
    commit-message:
      prefix: 'ci'
      prefix-development: 'ci'
      include: 'scope'
