name: Acceptance Tests
concurrency:
  group: acceptance-tests
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
    - 'LICENSE'
    - 'GNUmakefile'
    - 'website/**'
    - 'docs/**'
    - '.changelog/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - uses: actions/cache@v2.1.7
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

    - name: Run acceptance tests
      run: make testacc
