name: Publish Terraform

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
  
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        fingerprint: ${{ secrets.GPG_FINGERPRINT }}
    - name: Publish
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --rm-dist
      env:
        GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
